[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[rpc_endpoints]
lattice = "http://localhost:8545"

[etherscan]
lattice = { key = "dummy", url = "http://localhost:8545" }
