[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
lattice = "http://localhost:8545"

[etherscan]
lattice = { key = "dummy", url = "http://localhost:8545" }
