# Lattice API Server Configuration
[server]
host = "0.0.0.0"
port = 3000

[mcp]
enabled = true
host = "0.0.0.0"
port = 3001

[node]
rpc_url = "http://lattice-node:8545"
ws_url = "ws://lattice-node:8546"

[database]
url = "postgresql://lattice:lattice@postgres:5432/lattice"
max_connections = 10

[redis]
url = "redis://redis:6379"

[ipfs]
api_url = "http://ipfs:5001"
gateway_url = "http://ipfs:8080"

[logging]
level = "info"
format = "json"