[chain]
chain_id = 1337
genesis_hash = ""
block_time = 1
ghostdag_k = 8

[network]
listen_addr = "0.0.0.0:30303"
bootstrap_nodes = []
max_peers = 50

[rpc]
enabled = true
listen_addr = "0.0.0.0:8545"
ws_addr = "0.0.0.0:8546"

[storage]
data_dir = ".citrate-devnet"
pruning = false
keep_blocks = 1000

[mining]
enabled = true
coinbase = "0000000000000000000000000000000000000000000000000000000000000000"
target_block_time = 1
min_gas_price = 1000000000
