version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: lattice-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - lattice-monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: lattice-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=lattice123
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    networks:
      - lattice-monitoring
    depends_on:
      - prometheus

networks:
  lattice-monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
