global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lattice-node'
    metrics_path: /metrics
    static_configs:
      - targets: ['lattice-node-devnet:9100']
      - targets: ['lattice-node-1:9100','lattice-node-2:9100','lattice-node-3:9100','lattice-node-4:9100','lattice-node-5:9100']
