version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lattice-explorer-db
    environment:
      POSTGRES_DB: lattice_explorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: lattice-explorer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  explorer:
    image: node:20-alpine
    container_name: lattice-explorer
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/lattice_explorer
      REDIS_URL: redis://redis:6379
      RPC_ENDPOINT: ${RPC_ENDPOINT:-http://host.docker.internal:8545}
      NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: sh -c "apk add --no-cache bash curl && npm ci && npx prisma generate && npm run dev"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  indexer:
    image: node:20-alpine
    container_name: lattice-indexer
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/lattice_explorer
      RPC_ENDPOINT: ${RPC_ENDPOINT:-http://host.docker.internal:8545}
      INDEXER_ENABLED: "true"
    volumes:
      - ./:/app
    command: sh -c "npm ci && npx prisma generate && npm run indexer"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
