[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]

[rpc_endpoints]
lattice = "http://localhost:8545"

[etherscan]
lattice = { key = "${ETHERSCAN_API_KEY}" }

# Lattice-specific configurations
[profile.lattice]
via_ir = true
optimizer = true
optimizer_runs = 10000