# Citrate Node Configuration
[network]
listen_addr = "0.0.0.0:30303"
boot_nodes = []
max_peers = 50

[rpc]
enabled = true
listen_addr = "0.0.0.0:8545"
cors_origins = ["*"]
max_connections = 100

[ws]
enabled = true
listen_addr = "0.0.0.0:8546"
cors_origins = ["*"]
max_connections = 100

[consensus]
protocol = "ghostdag"
k = 18
finality_depth = 12

[execution]
vm_type = "evm"
gas_limit = 30000000
gas_price = 1000000000

[storage]
data_dir = "/data"
cache_size = 1024

[logging]
level = "info"
format = "json"