name: GUI Tauri CI

on:
  push:
    paths:
      - 'citrate/gui/lattice-core/**'
      - '.github/workflows/gui-tauri.yml'
      - 'citrate/core/**'
      - 'citrate/wallet/**'
      - 'citrate/node/**'
  pull_request:
    paths:
      - 'citrate/gui/lattice-core/**'
      - '.github/workflows/gui-tauri.yml'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: citrate/gui/lattice-core

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: citrate/gui/lattice-core/package-lock.json

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libssl-dev

      - name: Install frontend deps
        run: npm ci

      - name: Build Tauri app
        run: npm run tauri:build

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: lattice-core-tauri-${{ matrix.os }}
          path: |
            citrate/target/release/bundle/**
          if-no-files-found: warn

