name: Rust CI

on:
  push:
    paths:
      - 'citrate/**'
      - '.github/workflows/rust-ci.yml'
  pull_request:
    paths:
      - 'citrate/**'
      - '.github/workflows/rust-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: citrate
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Show toolchain
        run: rustc -Vv && cargo -V
      - name: Build tests (no run) — exclude GUI crate
        run: cargo test --workspace --exclude lattice-core --no-run
      - name: Run tests — exclude GUI crate
        run: cargo test --workspace --exclude lattice-core --quiet

  verifier-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: citrate
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Show toolchain
        run: rustc -Vv && cargo -V
      - name: Build lattice-api with verifier feature
        run: cargo build -p lattice-api --features verifier-ethers-solc
      - name: Run lattice-api tests with verifier feature
        run: cargo test -p lattice-api --features verifier-ethers-solc -- --nocapture
